/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.common.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.macro.mall.common.api.CommonResult;
import com.macro.mall.common.api.IErrorCode;
import com.macro.mall.common.exception.ApiException;
import com.macro.mall.common.exception.GlobalExceptionHandler;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;
import org.springframework.core.MethodParameter;
import org.springframework.validation.BindException;
import org.springframework.validation.BindingResult;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class GlobalExceptionHandler_SSTest extends GlobalExceptionHandler_SSTest_scaffolding {
// allCoveredLines:[17, 22, 23, 25, 31, 32, 33, 34, 35, 36, 39, 45, 46, 47, 48, 49, 50, 53]

  @Test(timeout = 4000)
  public void test_handle_0()  throws Throwable  {
      //caseID:df22ccb2a5306cde23992bceb1be252e
      //CoveredLines: [17, 22, 23]
      //Input_0_ApiException: iErrorCode0
      //Assert: assertEquals(0L, method_result.getCode());
      
      GlobalExceptionHandler globalExceptionHandler0 = new GlobalExceptionHandler();
      //mock iErrorCode0
      IErrorCode iErrorCode0 = mock(IErrorCode.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      ApiException apiException0 = new ApiException(iErrorCode0);
      
      //Call method: handle
      CommonResult commonResult0 = globalExceptionHandler0.handle(apiException0);
      
      //Test Result Assert
      assertEquals(0L, commonResult0.getCode());
  }

  @Test(timeout = 4000)
  public void test_handle_1()  throws Throwable  {
      //caseID:0ae405baeea43a272af6f32710a0db83
      //CoveredLines: [17, 22, 25]
      //Input_0_ApiException: \"\"
      //Assert: assertEquals(500L, method_result.getCode());
      
      GlobalExceptionHandler globalExceptionHandler0 = new GlobalExceptionHandler();
      ApiException apiException0 = new ApiException("");
      
      //Call method: handle
      CommonResult commonResult0 = globalExceptionHandler0.handle(apiException0);
      
      //Test Result Assert
      assertEquals(500L, commonResult0.getCode());
  }

  @Test(timeout = 4000)
  public void test_handleValidException_2()  throws Throwable  {
      //caseID:82a853fe514de5da6ee32c04d05bc39b
      //CoveredLines: [17, 31, 32, 33, 39]
      //Input_0_MethodArgumentNotValidException: methodParameter0, bindingResult0
      //Assert: assertEquals(404L, method_result.getCode());
      
      GlobalExceptionHandler globalExceptionHandler0 = new GlobalExceptionHandler();
      //mock methodParameter0
      MethodParameter methodParameter0 = mock(MethodParameter.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock bindingResult0
      BindingResult bindingResult0 = mock(BindingResult.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      MethodArgumentNotValidException methodArgumentNotValidException0 = new MethodArgumentNotValidException(methodParameter0, bindingResult0);
      
      //Call method: handleValidException
      CommonResult commonResult0 = globalExceptionHandler0.handleValidException(methodArgumentNotValidException0);
      
      //Test Result Assert
      assertEquals(404L, commonResult0.getCode());
  }

  @Test(timeout = 4000)
  public void test_handleValidException_3()  throws Throwable  {
      //caseID:39027d1d7fa78f3e9cf13a02abd48418
      //CoveredLines: [17, 45, 46, 47, 53]
      //Input_0_BindException: globalExceptionHandler0, \"com.macro.mall.common.exception.GlobalExceptionHandler\"
      //Assert: assertEquals(404L, method_result.getCode());
      
      GlobalExceptionHandler globalExceptionHandler0 = new GlobalExceptionHandler();
      BindException bindException0 = new BindException(globalExceptionHandler0, "com.macro.mall.common.exception.GlobalExceptionHandler");
      
      //Call method: handleValidException
      CommonResult commonResult0 = globalExceptionHandler0.handleValidException(bindException0);
      
      //Test Result Assert
      assertEquals(404L, commonResult0.getCode());
  }

  @Test(timeout = 4000)
  public void test_handleValidException_4()  throws Throwable  {
      //caseID:fe2788662b04dc6fc32a77ccecf6831f
      //CoveredLines: [17, 31, 32, 33, 34, 35, 39]
      //Input_0_MethodArgumentNotValidException: methodParameter0, bindingResult0
      //Assert: assertEquals(404L, method_result.getCode());
      
      GlobalExceptionHandler globalExceptionHandler0 = new GlobalExceptionHandler();
      //mock methodParameter0
      MethodParameter methodParameter0 = mock(MethodParameter.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock bindingResult0
      BindingResult bindingResult0 = mock(BindingResult.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(true).when(bindingResult0).hasErrors();
      MethodArgumentNotValidException methodArgumentNotValidException0 = new MethodArgumentNotValidException(methodParameter0, bindingResult0);
      
      //Call method: handleValidException
      CommonResult commonResult0 = globalExceptionHandler0.handleValidException(methodArgumentNotValidException0);
      
      //Test Result Assert
      assertEquals(404L, commonResult0.getCode());
  }

  @Test(timeout = 4000)
  public void test_handleValidException_5()  throws Throwable  {
      //caseID:205765299e007c43a415298f839141ac
      //CoveredLines: [17, 45, 46, 47, 48, 49, 53]
      //Input_0_BindException: globalExceptionHandler0, \"com.macro.mall.common.exception.GlobalExceptionHandler\"
      //Assert: assertNull(method_result.getMessage());
      
      GlobalExceptionHandler globalExceptionHandler0 = new GlobalExceptionHandler();
      BindException bindException0 = new BindException(globalExceptionHandler0, "com.macro.mall.common.exception.GlobalExceptionHandler");
      
      bindException0.reject("com.macro.mall.common.exception.GlobalExceptionHandler", "com.macro.mall.common.exception.GlobalExceptionHandler");
      
      //Call method: handleValidException
      CommonResult commonResult0 = globalExceptionHandler0.handleValidException(bindException0);
      
      //Test Result Assert
      assertNull(commonResult0.getMessage());
  }

  @Test(timeout = 4000)
  public void test_handleValidException_6()  throws Throwable  {
      //caseID:a7642fef071c12af7705bacc3047ea8c
      //CoveredLines: [17, 31, 32, 33, 34, 35, 36, 39]
      //Input_0_MethodArgumentNotValidException: methodParameter0, bindingResult0
      //Assert: assertEquals("nullnull", method_result.getMessage());
      
      GlobalExceptionHandler globalExceptionHandler0 = new GlobalExceptionHandler();
      //mock methodParameter0
      MethodParameter methodParameter0 = mock(MethodParameter.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock fieldError0
      FieldError fieldError0 = mock(FieldError.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock bindingResult0
      BindingResult bindingResult0 = mock(BindingResult.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(fieldError0).when(bindingResult0).getFieldError();
      doReturn(true).when(bindingResult0).hasErrors();
      MethodArgumentNotValidException methodArgumentNotValidException0 = new MethodArgumentNotValidException(methodParameter0, bindingResult0);
      
      //Call method: handleValidException
      CommonResult commonResult0 = globalExceptionHandler0.handleValidException(methodArgumentNotValidException0);
      
      //Test Result Assert
      assertEquals("nullnull", commonResult0.getMessage());
  }

  @Test(timeout = 4000)
  public void test_handleValidException_7()  throws Throwable  {
      //caseID:9109ce27c53daf9493a16696b7ebce18
      //CoveredLines: [17, 45, 46, 47, 48, 49, 50, 53]
      //Input_0_BindException: bindingResult0
      //Assert: assertEquals("nullnull", method_result.getMessage());
      
      GlobalExceptionHandler globalExceptionHandler0 = new GlobalExceptionHandler();
      //mock fieldError0
      FieldError fieldError0 = mock(FieldError.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock bindingResult0
      BindingResult bindingResult0 = mock(BindingResult.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(fieldError0).when(bindingResult0).getFieldError();
      doReturn(true).when(bindingResult0).hasErrors();
      BindException bindException0 = new BindException(bindingResult0);
      
      //Call method: handleValidException
      CommonResult commonResult0 = globalExceptionHandler0.handleValidException(bindException0);
      
      //Test Result Assert
      assertEquals("nullnull", commonResult0.getMessage());
  }
}
